---
title: "wrangle_nitrate_data"
author: "Reina Scott"
date: "2024-03-19"
output: html_document
---
load packages 
```{r}

library(tidyverse)
library(neonUtilities)
library(here)
```

name objects
```{r}
nitrate <- "DP1.20033.001"

my_sites <- c("TOOK", "CRAM", "PRLA")
```

pull data from neon 
```{r}
list2env(loadByProduct(dpID = nitrate, 
                        site = my_sites, 
                        include.provisional = FALSE),
         .GlobalEnv)
```
save data to raw data folder 
```{r}
variables_20033 %>% 
  write_csv(here("data", "raw", "variables_20033.csv"))

NSW_15_minute %>% 
  write_csv(here("data", "raw", "NSW_15_minute.csv"))

```

wrangle data 
```{r}
SW_Nitrate<- read.csv(here("data", "raw", "NSW_15_minute.csv"))

SW_Nitrate_means_noNAs<- SW_Nitrate %>% 
  select(siteID, surfWaterNitrateMean, startDateTime, endDateTime) %>% 
  arrange(siteID) %>% 
  na.omit(SW_Nitrate_means)
```
group by year and month and get means of years 
```{r}
SW_Nitrate_means <- SW_Nitrate_means_noNAs %>% 
  mutate(collectDate = as_date(endDateTime)) %>% 
  mutate(collectMonth = month(endDateTime), collectYear = year(endDateTime)) %>% 
 group_by(siteID, collectYear, collectMonth) %>% 
  summarise(mean_SWN = mean(surfWaterNitrateMean))
```
save data 
```{r}
SW_Nitrate_means %>% 
  write_csv(here("data", "processed", "SW_Nitrate_means.csv"))
```

name objects
```{r}
waterqual <- "DP1.20093"
my_sites1 <- c("TOOK", "CRAM", "PRLA")
```
pull data from neon 
```{r}
list2env(loadByProduct(dpID = waterqual, 
                        site = my_sites1, 
                        include.provisional = TRUE),
         .GlobalEnv)
```

save data to raw data folder 
```{r}
variables_20093 %>% 
  write_csv(here("data", "raw", "variables_20093.csv"))

swc_externalLabDataByAnalyte %>% 
  write_csv(here("data", "raw", "nutrientdata.csv"))

```

wrangle data 
```{r}
nutrientdata<- read.csv(here("data", "raw", "nutrientdata.csv"))

nutrientdata_noNAs<- nutrientdata %>% 
  select(siteID, analyte, analyteConcentration, analyteUnits, collectDate) %>% 
  arrange(siteID) %>% 
  subset(analyte == c("TN", "TP", "Ortho-P", "NH4 - N", "NO3+NO2 - N" )) %>% 
  group_by(analyte) %>% 
  na.omit(nutrientdata)
```
create objects for each nutrient data 
```{r}
#create new dataframe to use 
nutrientdataALL <- nutrientdata %>% 
  select(siteID, analyte, analyteConcentration, analyteUnits, collectDate) %>% 
  arrange(siteID) %>% 
  subset(analyte == c("TN", "TP", "Ortho - P", "NH4 - N", "NO3+NO2 - N" )) %>% 
  group_by(analyte) 


#Total Nitrate
nutrientdataTN <- nutrientdataALL %>% 
  subset(analyte == "TN") %>% 
  rename(TNConcentration_mgL = analyteConcentration) %>% 
  subset(select = -analyte) %>% 
  subset(select = -analyteUnits) %>% 
  na.omit(nutrientdataALL)

#Total Phosphate 
nutrientdataTP <- nutrientdataALL %>% 
  subset(analyte == "TP") %>% 
  rename(TPConcentration_mgL = analyteConcentration) %>% 
  subset(select = -analyte) %>% 
  subset(select = -analyteUnits) %>% 
    na.omit(nutrientdataALL)


#Ortho-P 
nutrientdataOrthoP <- nutrientdataALL %>% 
  subset(analyte == "Ortho - P") %>% 
  rename(OrthoPConcentration_mgL = analyteConcentration) %>% 
  subset(select = -analyte) %>% 
  subset(select = -analyteUnits) %>%  
  na.omit(nutrientdataALL)

#NH4-N 
nutrientdataNH4 <- nutrientdataALL %>% 
  subset(analyte == "NH4 - N") %>% 
  rename(NH4Concentration_mgL = analyteConcentration) %>% 
  subset(select = -analyte) %>% 
  subset(select = -analyteUnits) %>% 
    na.omit(nutrientdataALL)

#NO3+NO2-N
nutrientdataNO3NO2 <- nutrientdataALL %>% 
  subset(analyte == "NO3+NO2 - N") %>% 
  rename(NO3NO2Concentration_mgL = analyteConcentration) %>% 
  subset(select = -analyte) %>% 
  subset(select = -analyteUnits) %>% 
    na.omit(nutrientdataALL)
```
merge all of the datasets together
```{r}
finalnutrientdata<- full_join(nutrientdataNO3NO2, nutrientdataNH4, by = c("siteID", "collectDate")) %>% 
  full_join(nutrientdataOrthoP, by = c("siteID", "collectDate")) %>% 
  full_join(nutrientdataTP, by = c("siteID", "collectDate")) %>% 
 full_join(nutrientdataTN, by = c("siteID", "collectDate"))
```

group by year and month and get means of years 
```{r}
finalnutrientdatamena <- finalnutrientdata %>% 
 group_by(siteID, collectDate) %>% 
  summarise(mean_TN_Con_mgL = mean(TNConcentration_mgL), 
            mean_TP_Con_mgL = mean(TPConcentration_mgL), 
            mean_NH4_Con_mgL = mean(NH4Concentration_mgL), 
            mean_OrthoP_Con_mgL = mean(OrthoPConcentration_mgL), 
            mean_NO3NO2_Con_mgL = mean(NO3NO2Concentration_mgL) )
```
save data 
```{r}
finalnutrientdatamena %>% 
  write_csv(here("data", "processed", "nutrient_data_means.csv"))
```
