---
title: "Water Qual Wrangling"
author: "Niko"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load the tidyverse package
# Load the here package

library(here)
library(tidyverse)

```


```{r}
# Read in raw data
water_qual <- read_csv(here("data", "raw", "waq_instantaneous.csv"))

# Preview the data
head(water_qual)
```

```{r}
# Subset by variables and drop NAs
subset_waterqual <- water_qual %>% 
  mutate(collectDate = as_date(floor_date(endDateTime, "month"))) %>%
  select(siteID, collectDate, pH, chlorophyll, dissolvedOxygen) %>%
  drop_na() %>% 
  arrange(siteID)

head(subset_waterqual)
```

change data and time and organize by means 
```{r}

waterqual_means <- subset_waterqual %>% 
  group_by(siteID, collectDate) %>% 
  summarise(mean_pH = mean(pH), 
            mean_DO = mean(dissolvedOxygen), 
            mean_chlorophyll= mean(chlorophyll))

head(waterqual_means)

```

```{r}
waterqual_means %>%
  write_csv(here("data", "processed", "waterqual_means.csv"))
```
